jobs:
  - job: distro_release
    displayName: distro

    pool:
      name: MLNX
      demands:
        - harbor_registry -equals yes

    strategy:
      matrix:
        centos7_cuda10_1:
          build_container: centos7_cuda10_1
          artifact_name: centos7-cuda10.1.tar
        centos7_cuda10_2:
          build_container: centos7_cuda10_2
          artifact_name: centos7-cuda10.2.tar
        ubuntu16_cuda10_1:
          build_container: ubuntu16_cuda10_1
          artifact_name: ubuntu16.04-cuda10.1.deb
        ubuntu16_cuda10_2:
          build_container: ubuntu16_cuda10_2
          artifact_name: ubuntu16.04-cuda10.2.deb
        ubuntu18_cuda10_1:
          build_container: ubuntu18_cuda10_1
          artifact_name: ubuntu18.04-cuda10.1.deb
        ubuntu18_cuda10_2:
          build_container: ubuntu18_cuda10_2
          artifact_name: ubuntu18.04-cuda10.2.deb

    container: $[ variables['build_container'] ]

    steps:
      - checkout: self
        clean: true
        path: "we/need/to/go/deeper"

      - bash: |
          set -eE
          ./autogen.sh
          ./contrib/configure-release --with-cuda
        displayName: Configure

      - bash: |
          set -eE
          ./contrib/buildrpm.sh -s -t -b
          tar -C rpm-dist/`uname -m` -czf "${AZ_ARTIFACT_NAME}" .
        displayName: Build package
        condition: startsWith(variables['artifact_name'], 'centos')
        env:
          AZ_ARTIFACT_NAME: $(artifact_name)

      - bash: |
          set -eE
          dpkg-buildpackage -us -uc
          find .. -name '*.deb' -exec cp {} "${AZ_ARTIFACT_NAME}" \;
        displayName: Build package
        condition: startsWith(variables['artifact_name'], 'ubuntu')
        env:
          AZ_ARTIFACT_NAME: $(artifact_name)

      - task: GithubRelease@0
        displayName: Create/edit GitHub Draft Release
        inputs:
          githubConnection: release
          repositoryName: openucx/ucx
          action: edit
          tag: $(Build.SourceBranchName)
          isDraft: true
          addChangeLog: false
          assetUploadMode: replace
          assets: "./$(artifact_name)"
